<h1 align='center'><font color='red'> Task_4


1. [NumPy](#NumPy)
1. [oop](#oop)
3. [ProblemSolving](#ProblemSolving)


<a id='NumPy'></a>
<h1><font color='red'> NumPy

## 1.What does NumPy stand for?


#### A) Number Python
#### B)Numerator Python
#### C) Numerical Python
#### D)There is no full form, it is a stand-alone word  


In [1]:
A = False #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = True #@param {type:"boolean"}
D = False #@param {type:"boolean"}


## 2.What does the size attribute in numpy use to find?


#### A) number of items
#### B)shape
#### C) date & time
#### D)unique items
    

In [3]:
A = True #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}

In [2]:
import numpy as np
arr = np.array([[1,2,3], [2,3,4]])
print(arr.size)

6


### 3.What is the purpose of zero() function?

#### A) To create a matrix with the first row and first column as 0
#### B) To create a matrix with diagonal elements as 0
#### C) To create a matrix with all elements as 0
#### D) To return an integer number 0


In [ ]:
A = False #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = True #@param {type:"boolean"}
D = False #@param {type:"boolean"}

In [8]:
arr = np.zeros((3,2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


<h1><font color='red'> Answer these question

### 4- create 1D, 2D and 3D arrays in NumPy? then returns the type of the elements stored in the NumPy array.

In [9]:
# One-Dimensional array
arr = np.arange(1,6)
print(arr , arr.dtype)





[1 2 3 4 5] int32


In [10]:
# Two-Dimensional array
arr = np.array([[1,3,5],[2,4,6],[2,3,5]])
print(arr , arr.dtype)





[[1 3 5]
 [2 4 6]
 [2 3 5]] int32


In [11]:
# Three-Dimensional array

shape = (1,3,4)
arr = np.ones(shape)
print(arr , arr.dtype)



[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]] float64


### 5-Reverse this array [[[1,2,3,4],[4,5,6,7],[7,8,9,10]]] in two ways......

In [35]:
# Method one
arr = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,10]]])
print(arr)
#arr1 = arr.reshape((12))
#print(arr1)
arr2 = arr[::-1,::-1]
print(arr2)
#arr3 = arr1.reshape((1,3,4))
#print(arr3)




[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 7  8  9 10]]]
[[[ 7  8  9 10]
  [ 4  5  6  7]
  [ 1  2  3  4]]]


In [20]:
# Method two
#>**hint**: use flipud function
arr = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,10]]])
print(arr)
arr2 = np.fliplr(arr)
print(arr2)




[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 7  8  9 10]]]
[[[ 7  8  9 10]
  [ 4  5  6  7]
  [ 1  2  3  4]]]


## 6-Make this array as an array one dimensional

In [39]:
print(arr)
print(arr.reshape((12)))

[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 7  8  9 10]]]
[ 1  2  3  4  4  5  6  7  7  8  9 10]


## 7- Create a 3X2 integer array and Prints its attributes¶
* Note: The element must be a type of unsigned int16. And print the following Attributes:

- The shape of an array.
- Array dimensions.
- The Length of each element of the array in bytes

In [49]:
arr = np.empty((3,2),dtype=np.int16)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.itemsize)

[[257 257]
 [257 257]
 [257 257]]
(3, 2)
2
2


### 8- Return array of odd rows and even columns from below numpy array

* # Ordering the values of each Key and the print the key witht highest value.


> **`sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])`**


# The output should be:
* `expexted output :
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]`

* `Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]`*

In [56]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(np.sort(sampleArray,axis=0))
print(sampleArray[::2,1::2])


[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
[[ 6 12]
 [30 36]
 [54 60]]


## 9-How is np.mean() different from np.average() in NumPy?

In [ ]:
#They are frequently used interchangeably, but they should not even be.  
#The np.mean() method returns the arithmetic mean, 
#but the np.average() function returns the algebraic mean if no additional parameters are specified, 
#but it may also be used to compute a weighted average.

## 10-Count the frequency of a given positive value appearing in this NumPy array
## [1, 2, 1, 3, 5, 0, 0, 0, 2, 3] ?

In [59]:
arr = np.array([1, 2, 1, 3, 5, 0, 0, 0, 2, 3])
count = 0 
for i in arr:
    if i >= 0 :
        count += 1
print(count)

10


In [60]:
arr = np.array([1, 2, 1, 3, 5, 0, 0, 0, 2, 3])
(arr>=0).sum()

10

## 11-Show how is arr[:,0] different from arr[:,[0]]

In [66]:
arr = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(arr[:,0])
arr[:,0].shape

[ 3 15 27 39 51]


(5,)

In [67]:
arr = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(arr[:,[0]])
arr[:,[0]].shape

[[ 3]
 [15]
 [27]
 [39]
 [51]]


(5, 1)

### 12-How do you multiply these 2 NumPy array matrices [[15,16,17],[18,19,20],[21,22,23]]  &  [[20,21,22],[23,24,25],[26,27,28]] ?

In [68]:
arr1 = np.array([[15,16,17],[18,19,20],[21,22,23]])
arr2 = np.array([[20,21,22],[23,24,25],[26,27,28]])
print(arr1 * arr2)

[[300 336 374]
 [414 456 500]
 [546 594 644]]


### 13 -Combine these 2 NumPy arrays [1,2,3] & [4,5,6] using vstack()     and hstack()

In [72]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.vstack([arr1, arr2]))

[[1 2 3]
 [4 5 6]]


In [73]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.hstack([arr1, arr2]))

[1 2 3 4 5 6]


# <a id='oop'></a>
<h1><font color='red'> oop

# 1 - a "class" is ... </font>

<br> </br>
#### A) an instance variable
#### B) a code template for creating object
#### C) a function in python
#### D) a synonym for methods

In [74]:
A = False #@param {type:"boolean"}
B = True #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}


# 2- What is a "docstring" ?</font>
<br> </br>
#### A) it is a sting literal specified in source code that is used to explain or document a specific segment of code
#### B) it is a class method that allows working with string documents
#### C) it is an alternative name for instance vaeiables of type string apprearing in classes
#### D) it is a synonym for code comments

In [75]:
A = True #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}


In [ ]:
def square(n):
    return n**2

## 3- Create a Bus class that inherits from the Vehicle class. Give the capacity argument of Bus.seating_capacity() a default value of 50.
- Use the following code for your parent Vehicle class:.
>   class Vehicle:
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage
    def seating_capacity(self, capacity):
        return f"The seating capacity of a {self.name} is {capacity} passengers


In [76]:
class Vehicle:
    def __init__(self , name , max_speed , mileage ):
        self.name = name 
        self.max_speed = max_speed
        self.mileage = mileage
    def seating_capacity(self , capacity):
        return f"The seating capacity of a {self.name} is {capacity} passengers"
    
class Bus(Vehicle):
    def __init__(self, name, max_speed, mileage):
        super().__init__(name, max_speed, mileage)
    def seating_capacity(self, capacity=50):
        return super().seating_capacity(capacity=50)

The seating capacity of a mmmm is 50 passengers


# <a id='ProblemSolving'></a>
<h1><font color='red'>Problem Solving


<a href='https://codeforces.com/problemset/problem/339/A'> **problem 1**

In [81]:
# Problem_1 Link:
#https://codeforces.com/problemset/submission/339/217444297
num = input()
numlist = num.split('+')
numlist.sort()
print('+'.join(numlist))


<a href='https://codeforces.com/problemset/problem/118/A'> **problem 2**

In [85]:
# Problem_2 Link:
#https://codeforces.com/problemset/submission/118/217482411
str1 = input()
str1 = str1.lower()
s = ""
L = ['a', 'e', 'i', 'o', 'u', 'y']
for i in range(0, len(str1)):
    if str1[i] not in L:
        s += '.'
        s += str1[i]
 
print(s)

